# syntax=docker/dockerfile:1
FROM golang:1.21.4 AS build-stage

WORKDIR /app

COPY . ./.
RUN go mod download


RUN CGO_ENABLED=0 GOOS=linux go build -o /nester

FROM build-stage AS run-test-stage
RUN go test -v ./...

FROM alpine:3.16.2 AS production-stage

WORKDIR /

COPY --from=build-stage /nester /nester

ENTRYPOINT ["/nester"]
