name: docker

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push nester
        uses: docker/build-push-action@v5
        with:
          context: Dockerfile.nester
          push: true
          tags: donaldgifford/nester:latest
      - name: Build and push custom caddy
        uses: docker/build-push-action@v5
        with:
          context: Dockerfile.Caddy
          push: true
          tags: donaldgifford/nester-caddy:latest
